workflows:
    testflight-workflow:
        name: Testflight Workflow
        scripts:
            - name: CI/CD Started
              script: echo "Welcome to CI/CD pipeline"
        publishing:
            email:
                recipients:
                    - wshidayat38@gmail.com
