workflows:
    testflight-workflow:
        name: Testflight Workflow
        scripts:
            - name: CI/CD Started
              script: echo "Welcome to CI/CD pipeline"
            - name: iOS test
              script: xcode-project run-tests --project TriangleApp.xcodeproj --scheme TriangleApp --device "iPhone 15"
              test_report: build/ios/test/*.xml
        publishing:
            email:
                recipients:
                    - wshidayat38@gmail.com
