workflows:
  testflight-workflow:
    name: Testflight Workflow
    environment:
      groups:
        - Admin
    scripts:
      - name: CI/CD Started
        script: echo "Welcome to CI/CD pipeline"
      - name: Run Unit Test
        script: xcode-project run-tests --project TriangleApp.xcodeproj --scheme TriangleApp --device "iPhone 15"
        test_report: build/ios/test/*.xml
      - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
        script: keychain initialize
      - name: Fetch signing files
        script: app-store-connect fetch-signing-files "com.wakhidhidayat.TriangleApp" --type IOS_APP_STORE --create
      - name: Set up signing certificate
        script: keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Build IPA
        script: xcode-project build-ipa --project "TriangleApp.xcodeproj"
        #- name: Run Build
          #script: xcodebuild build -project "TriangleApp.xcodeproj" -scheme "TriangleApp" CODE_SIGN_INDENTITY="" CODE_STONING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        beta_groups:
         - YTTA
      email:
        recipients:
          - wshidayat38@gmail.com
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - SHOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
