workflows:
  testflight-workflow:
    name: Testflight Workflow
      scripts:
        - name: CI/CD Started
          script: echo "Welcome to CI/CD pipeline"
        - name: Run Unit Test
          script: xcode-project run-tests --project TriangleApp.xcodeproj --scheme TriangleApp --device "iPhone 15"
          test_report: build/ios/test/*.xml
        - name: Set up keychain to be used for code signing using Codemagic CLI 'keychain' command
          script: keychain initialize
        - name: Fetch signing files
          script: app-store-connect fetch-signing-files "com.wakhidhidayat.TriangleApp" --type IOS_APP_STORE --create
        - name: Set up signing certificate
          script: keychain add-certificates
        - name: Set up code signing settings on Xcode project
          script: xcode-project use-profiles
        - name: Build IPA
          script: xcode-project build-ipa --project "TriangleApp.xcodeproj" —-scheme "TriangleApp"
        #- name: Run Build
          #script: xcodebuild build -project "TriangleApp.xcodeproj" -scheme "TriangleApp" CODE_SIGN_INDENTITY="" CODE_STONING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      publishing:
        email:
          recipients:
            - wshidayat38@gmail.com
      artifacts:
        - build/ios/ipa/*.ipa
        - /tmp/xcodebuild_logs/*.log
        - SHOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
